Player=mpv
SkipFiller=true
NextEpisodePrompt=false
DiscordPresence=true
ScoreOnCompletion=true
ImagePreview=false
SaveMpvSpeed=true
DiscordClientId=1287457464148820089
TrackingConfigured=true
MyAnimeListImportDismissed=false
StoragePath=$HOME/.local/share/curd
SkipOp=true
SkipRecap=true
MyAnimeListImported=false
MpvArgs=[]
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,CONTINUE_LAST,TRACKER,PROVIDER
MyAnimeListClientID=f76d4c827152327b60654285d221222c
TrackingRemote=anilist
PercentageToMarkComplete=85
SubsLanguage=english
SkipEd=true
Provider=["allanime"]
AlternateScreen=true
AnimeNameLanguage=english
SubOrDub=sub
TrackingLocal=true
AddMissingOptions=true
RofiSelection=false
MyAnimeListClientSecret=
