
$mainMod = SUPER

exec-once = hyprpm reload -n

general {
  layout = scrolling
}

plugin {
  hyprscrolling {
      column_width = 0.5
      fullscreen_on_one_column = false
      focus_fit_method = 0
      explicit_column_widths = 0.3, 0.5, 0.7, 1.0
      smart_resizing = true
    }
}

bind = $mainMod, period, layoutmsg, move +col
bind = $mainMod, comma, layoutmsg, move -col
bind = $mainMod SHIFT, period, layoutmsg, movewindowto r
bind = $mainMod SHIFT, comma, layoutmsg, movewindowto l
bind = $mainMod SHIFT, up, layoutmsg, movewindowto u
bind = $mainMod SHIFT, down, layoutmsg, movewindowto d
bind = $mainMod, f, layoutmsg, togglefit
bind = $mainMod, r, layoutmsg, colresize +conf
bind = $mainMod, h, layoutmsg, colresize 0.5
